# gather up dependencies
find_package(PkgConfig QUIET)
find_package(OpenGL REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(SDL2 REQUIRED)
find_package(PNG REQUIRED)
find_package(jpeg REQUIRED)
find_package(zstd REQUIRED)
if (WIN32 OR APPLE)
    find_package(Ogg REQUIRED)
    find_package(Vorbis REQUIRED)
    find_package(unofficial-minizip CONFIG REQUIRED)
    find_package(mad CONFIG REQUIRED)
else ()
    pkg_search_module(minizip REQUIRED minizip)
    pkg_search_module(MAD REQUIRED mad)
endif()
