# gather up dependencies
find_package(PkgConfig QUIET)
find_package(OpenSSL REQUIRED)
find_package(SDL2 REQUIRED)
find_package(PNG REQUIRED)
find_package(jpeg REQUIRED)
find_package(zstd REQUIRED)
if (WIN32)
    find_package(unofficial-minizip CONFIG REQUIRED)
    find_package(mad CONFIG REQUIRED)
else ()
    pkg_search_module(minizip REQUIRED minizip)
    pkg_search_module(MAD REQUIRED mad)
endif()
