if (WIN32)
    foreach(file ${JQ_GASM})
        execute_process(cl.exe cl /nologo /EP > ${file}.spp ${file})
        execute_process(gas2masm.exe < ${file}.spp > ${file}.asm)
        execute_process(ml.exe /nologo /c /Cp /coff /Fo${file}.obj /Zm /Zi ${file}.asm)
    endforeach()
endif()
