if (WIN32)
    add_executable(gas2nasm thirdparty/gas2nasm/gas2nasm.c)
    foreach(file ${JQ_GASM})
        execute_process(cl.exe cl /nologo /EP > ${file}.spp ${file})
        execute_process(thirdparty/gas2masm/gas2masm.exe < ${file}.spp > ${file}.asm)
        execute_process(ml.exe /nologo /c /Cp /coff /Fo${file}.obj /Zm /Zi ${file}.asm)
    endforeach()
endif()
