name: Build JoeQuake

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install cmake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.0.0"
          ninjaVersion: "^1.0.0"

      - name: Set up dependencies (Linux)
        if: runner.os == "Linux"
        shell: bash
        run: |
          sudo apt install -y \
            libminizip-dev libssl-dev zlib1g-dev \
            libsdl2-dev libmad0-dev libpng-dev libjpeg-turbo8-dev libvorbis-dev

      - name: Set up dependencies (Win/Mac)
        if: runner.os != "Linux"
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/thirdparty/vcpkg

      # - name: Set vcpkg option
      #   shell: bash
      #   run: |
      #     if [[ "${{ matrix.runner }}" != "ubuntu"* ]]; then
      #       echo "ENABLE_VCPKG=ON" >> $GITHUB_ENV
      #     else
      #       echo "ENABLE_VCPKG=OFF" >> $GITHUB_ENV
      #     fi

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "Release"
          buildPreset: "Release"
