name: Build JoeQuake

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux-appimage:
    name: AppImage
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "dist/linux/AppImageBuilder.yml"
        env:
          UPDATE_INFO: gh-releases-zsync|j0zzz|joequake-1|latest|*AppImage.zsync
      - name: Store AppImage
        uses: actions/upload-artifact@v4
        with:
          path: *.AppImage

  linux:
    name: Linux build
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install cmake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.0.0"
          ninjaVersion: "^1.0.0"

      - name: Set up dependencies (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt update && sudo apt install -y \
            libminizip-dev libssl-dev zlib1g-dev \
            libsdl2-dev libmad0-dev libpng-dev libjpeg-turbo8-dev libvorbis-dev

      - name: Build
        shell: bash
        run: |
          cmake --preset Ninja -DENABLE_VCPKG=OFF --install-prefix=$(pwd)/build/AppDir
          cmake --build --preset RelWithDbgInfo
          cmake --install build --prefix=./build/AppDir

  windows:
    name: Windows build
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install cmake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.0.0"
          ninjaVersion: "^1.0.0"

      - name: Build
        shell: bash
        run: |
          cmake -G "Visual Studio 17 2022" -A Win32 -DENABLE_VCPKG=ON -B "build32"
          cmake --build build32 --config RelWithDbgInfo
