name: Build JoeQuake

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install cmake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.0.0"
          ninjaVersion: "^1.0.0"

      - name: Set up dependencies (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt install -y \
            libminizip-dev libssl-dev zlib1g-dev \
            libsdl2-dev libmad0-dev libpng-dev libjpeg-turbo8-dev libvorbis-dev

      - name: Configure
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            export ENABLE_VCPKG=OFF
          else
            export ENABLE_VCPKG=ON
          fi
          cmake --preset Ninja -DENABLE_VCPKG=${ENABLE_VCPKG}
      - name: Build
        shell: bash
        run: |
          cmake --build --preset RelWithDbgInfo

      # - name: Set up dependencies (Win/Mac)
      #   if: runner.os != 'Linux'
      #   uses: lukka/run-vcpkg@v11
      #   with:
      #     vcpkgDirectory: ${{ github.workspace }}/thirdparty/vcpkg
      #     vcpkgJsonGlob: "vcpkg.json"
      #     runVcpkgInstall: true

      # - name: Build
      #   uses: lukka/run-cmake@v10
      #   with:
      #     configurePreset: "Ninja"
      #     configurePresetAdditionalArgs: "['-DENABLE_VCPKG=${{ env.ENABLE_VCPKG }}']"
      #     buildPreset: "RelWithDbgInfo"
      #     # packagePreset: "default"

      # - name: Create AppImage
      #   uses: AppImageCrafters/build-appimage@master
      #   with:
      #     recipe: dist/linux/AppImageBuilder.yml
      #   env:
      #     UPDATE_INFO: gh-releases-zsync|${{ github.repository_owner }}|${{ github.repository }}|latest|*.AppImage.zsync
